import React from 'react';

export const metadata = {
  title: "Contact",
  description: "Generated by Gadget Galaxy",
};

const ContactUs = () => {
    return (
        <div>
            <h1>This is contact page</h1>
        </div>
    );
};

export default ContactUs;