import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/shared/Header";
import Footer from "./components/shared/Footer";
import ReduxProvider from "./redux/Provider";
import NextAuthSessionProvider from "@/providers/NextAuthSessionProvider";
import { ReactNode } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: {
    default: "Gadget Galaxy",
    template: "%s | Gadget Galaxy"
  },
  description: "Generated by Gadget Galaxy",
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-100`}
      >
        <NextAuthSessionProvider>
          <ReduxProvider>
            <div className="sticky top-0 z-50 bg-white/30 backdrop-blur-lg shadow-lg">
              <Header />
            </div>
            <main className="min-h-screen w-11/12 mx-auto">
              {children}
            </main>
            <Footer />
          </ReduxProvider>
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}